/**
 * Fixed schema for GitHub-backed lists.
 * Maps GitHub issue fields to ParsedField format.
 */

import { ParsedField } from './dsl-types';

export function getGitHubListSchema(): ParsedField[] {
  return [
    {
      propertyKey: 'number',
      propertyName: '#',
      propertyType: 'number',
      displayOrder: 0,
      isRequired: false,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'title',
      propertyName: 'Title',
      propertyType: 'text',
      displayOrder: 1,
      isRequired: true,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'body',
      propertyName: 'Body',
      propertyType: 'textarea',
      displayOrder: 2,
      isRequired: false,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'state',
      propertyName: 'State',
      propertyType: 'select',
      displayOrder: 3,
      isRequired: false,
      defaultValue: 'open',
      validationRules: { options: ['open', 'closed'] },
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'labels',
      propertyName: 'Labels',
      propertyType: 'multiselect',
      displayOrder: 4,
      isRequired: false,
      defaultValue: null,
      validationRules: { options: [] },
      helpText: 'Options loaded from repository',
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'assignees',
      propertyName: 'Assignees',
      propertyType: 'multiselect',
      displayOrder: 5,
      isRequired: false,
      defaultValue: null,
      validationRules: { options: [] },
      helpText: 'Options loaded from repository',
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'url',
      propertyName: 'Link',
      propertyType: 'url',
      displayOrder: 6,
      isRequired: false,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'created_at',
      propertyName: 'Created',
      propertyType: 'datetime',
      displayOrder: 7,
      isRequired: false,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
    {
      propertyKey: 'updated_at',
      propertyName: 'Updated',
      propertyType: 'datetime',
      displayOrder: 8,
      isRequired: false,
      defaultValue: null,
      validationRules: null,
      helpText: null,
      placeholder: null,
      isVisible: true,
      visibilityCondition: null,
    },
  ];
}
